version: "3.8"

services:
  dataintegration:
    image: docker.cmclinnovations.com/dataintegration:1.1.0-SNAPSHOT
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    environment:
      - STACK_NAME=${STACK_NAME}
      - DATABASE=postgres # currently ontop reads from the default database
    configs:
      - postgis
      - blazegraph
      - ontop
    secrets:
      - postgis_password
      - geoserver_password
    ports:
      - "8086:8080"
    volumes:
      - logs:/root/.jps
    networks:
      - stack
volumes:
  logs:
    name: "logs"