version: "3.8"

services:
  heat-instantiation:
    image: heat-instantiation:1.0.0-SNAPSHOT
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    build:
      target: production
    ports:
      - "5000:5000"
    volumes:
      - logs:/root/.jps

volumes:
  logs:
    name: "logs"
