#
# Compose file for the DTVF.
#
version: "3.8"

# All Services
services:

  # Empty DTVF visualisation image for deployment. Builds a base image that, when combined
  # with a volume of files, can be used as a visualisation. It is not intended that this
  # config is used to run the dtvf-base-image.
  visualise:
    image: ghcr.io/cambridge-cares/dtvf-base-image:latest
    container_name: "empty-dtvf-container"
    restart: "no"
    build:
      context: "./"
      dockerfile: "Dockerfile"
      labels:
        authors: "support@cmcl.io"
        description: "Empty visualisation image, ready to house web files."
    ports:
      - "80:80" 
