services:
  triton:
    build:
      context: triton
    env_file:
      - triton-variables.env
    shm_size: 256m
    ports:
      - 8000:8000
  chatbot:
    image: ghcr.io/abetlen/llama-cpp-python:latest
    volumes:
      - type: bind
        source: chatbot/models
        target: /models
    env_file:
      - chatbot-variables.env
    ports:
      - 8001:8000
  flask:
    build:
      context: flask
    env_file:
      - flask-variables.env
    ports:
      - 5000:5000
    depends_on:
      - triton